### ISSUE TITLE
Open-source schedule and baselins

### ISSUE THREAD

**Issue by SiyuanHuang95** [robopen/roboagent#1]
Hi,

thanks for your sharing, very impressive!

I would like to know your rough open-source time schedule.

BTW, could you also offer the community the baseline implementation, like RT-1 for a more convenient follow-up?

**Comment by homangab** [comment]
Thanks for the kind words. We are glad you like this work. We are planning to open-source code around end of September - will update here when we do! (we will provide the baseline implementation we used as well)

**Comment by SiyuanHuang95** [comment]
Glad to have your updates!

Will be looking for it!

**Comment by SiyuanHuang95** [comment]
Would there be any update? @homangab

**Comment by homangab** [comment]
sorry that our timeline is a bit delayed. we expect to release this in about 2 weeks. thank you for your patience.

**Comment by SiyuanHuang95** [comment]
Thanks for your update and information.
