### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by deavn2236** [robopen/roboagent#11]
Is there open-source code for the data augmentation part?

**Comment by homangab** [comment]
We will soon put out a script for doing the data augmentation in the repo (sorry for the delay in this)

**Comment by deavn2236** [comment]
Looking forward to your sharing, thank you very much

**Comment by mbreuss** [comment]
@homangab any updates regarding the planned release of the script?

**Comment by lanmmn** [comment]
@homangab still waiting for you, man

**Comment by homangab** [comment]
Apologies for not posting the update here - we were not able to obtain the required approvals from Meta for releasing the generative model based augmentation code due to some compliance rules.
