### ISSUE TITLE
Wipe counter data

### ISSUE THREAD

**Issue by AndreMouton** [robopen/roboagent#12]
I believe there may be a typo in the download link for the wipe counter teleop demos...

The link http://dl.fbaipublicfiles.com/RoboSet/TeleoperationSet/Activities/clean_kitchen/clean_kitchen_Wipe_Counter_Scene_3.tar.gz doesn't seem to work

**Comment by homangab** [comment]
Thanks for flagging - could you try out the links here instead? https://huggingface.co/datasets/jdvakil/RoboSet-Teleoperation/tree/main We have updated the Readme with this alternate set of links
