### ISSUE TITLE
Create my own dataset

### ISSUE THREAD

**Issue by deavn2236** [robopen/roboagent#13]
I hope to collect and create datasets through my own devices, such as using Aloha's Viper robotic arm and Widows robotic arm to collect my own dataset and run Roboagent. How can I create this dataset?

**Comment by Jdvakil** [comment]
Hey, thanks for reaching out! Once you have collected the dataset (i assume in pickle or h5 format), you could either convert them to roboset format (https://robopen.github.io/roboset/) or by modifying our data loader to accommodate your data format (eg https://github.com/robopen/roboagent/blob/e1ef61d3b51601f88c641636a40014d0790d156c/utils.py#L134-L141)

**Comment by Jdvakil** [comment]
If you want to convert your dataset to roboset format, I have some tools which could help you out

**Comment by lklimkiewicz7** [comment]
@Jdvakil  I would be interested in converting my dataset to roboset format. Could You share these "tools"?

**Comment by deavn2236** [comment]
> If you want to convert your dataset to roboset format, I have some tools which could help you out

Can you provide relevant tools? Thank you very much. Since roboagent has additional language input compared with aloha, how to deal with this part

**Comment by Jdvakil** [comment]
@deavn2236 @lklimkiewicz7 You can follow this [function](https://github.com/Jdvakil/data-tools/blob/d8ff7b00b2440b10fd8d4148e35003947868889e/utils/roboset/robohive2roboset.py#L22), here I converted a different dataset format to roboset. If you can extract the camera and proprioception values from your dataset, you would just need to replace them with the values in the dict

**Comment by Jdvakil** [comment]
> Since roboagent has additional language input compared with aloha, how to deal with this part
Which part?

**Comment by deavn2236** [comment]
> > 由于roboagent相比aloha多了额外的语言输入，这部分如何处理
> 
> @deavn2236 哪一部分？



> > Since roboagent has additional language input compared with aloha, how to deal with this part
> 
> @deavn2236 Which part?

You are directly using the task name as input for the language section. I would like to ask, without the language section, can it recognize multiple tasks solely through the input of the image feature extraction section? Have you tried this before and what is the effect

**Comment by Jdvakil** [comment]
@deavn2236 Yes, I tried it before and the agent usually tries to solve the task that matches the highest confidence of the initial setup. If the initial setup matches the closest to "close drawer" from the data, it will attempt to solve that

**Comment by deavn2236** [comment]
> @deavn2236 Yes, I tried it before and the agent usually tries to solve the task that matches the highest confidence of the initial setup. If the initial setup matches the closest to "close drawer" from the data, it will attempt to solve that

Will adding language (task name) as input make it easier for the system to execute the corresponding task? Will adding language have a higher success rate compared to directly distinguishing tasks through images?

**Comment by Jdvakil** [comment]
> Will adding language have a higher success rate compared to directly distinguishing tasks through images?
@deavn2236 Yes, adding language has a higher rate of success compared to just relying on visual feedback since there are multiple tasks on a single setup, the agent might get confused on what task to solve. 
Unless you are conditioning a single-task policy then language + visuals gives good success rates.
