### ISSUE TITLE
Finetune on new data

### ISSUE THREAD

**Issue by HM102** [robopen/roboagent#14]
Very good paper, thank you for the release.

How much data do you need to fine tune the model to work on new environment and task?

**Comment by Jdvakil** [comment]
To fine-tune a pre-trained model, ~25-75 trajectories should be good enough. 
We were able to get a new task in a new environment to work with ~25 trajectories fine-tuned

**Comment by HM102** [comment]
Thank you for the answer. This was with 4 cameras? did you try with 1 camera on real world data, how was the performance?
