### ISSUE TITLE
Question about ee pose in RoboSet

### ISSUE THREAD

**Issue by hhcaz** [robopen/roboagent#18]
Hi,

Thanks for your high quality dataset. According to the data schema of RoboSet, it contains the **"derived pose"** of robot link: 

<img width="997" alt="image" src="https://github.com/robopen/roboagent/assets/41253347/81478224-b42b-42ee-9d1c-ff64bcac0f99">

However, after downloading data from https://dl.fbaipublicfiles.com/RoboSet/TeleoperationSet/Activities/baking_prep/baking_prep_pick_butter_scene_4.tar.gz , I find there's no such key in the hdf5 file... 

```python
import h5py

file = "/mnt/raid5/data/roboset/v0.4/baking_prep/scene_4/baking_prep_pick_butter_scene_4/setting_table_pick_butter_scene_4_20230418-153322.h5"
with h5py.File(file, 'r') as h5:
    print("1:", h5.keys())
    print("2:", h5['Trial0'].keys())
    print("3:", h5['Trial0']['data'].keys())
```

This script outputs:
```
1: <KeysViewHDF5 ['Trial0', 'Trial10', 'Trial12', 'Trial14', 'Trial16', 'Trial18', 'Trial2', 'Trial4', 'Trial6', 'Trial8']>
2: <KeysViewHDF5 ['data']>
3: <KeysViewHDF5 ['ctrl_arm', 'ctrl_ee', 'd_left', 'd_right', 'd_top', 'd_wrist', 'qp_arm', 'qp_ee', 'qv_arm', 'qv_ee', 'rgb_left', 'rgb_right', 'rgb_top', 'rgb_wrist', 'time']>
```
The key "derived" is missing in the second line of output. Similar issue: #4 

Is there some way to get the pose (cartesian pos and quat) of the end effector? Should I compute it from joint positions using forward kinematics?

**Comment by homangab** [comment]
Thanks for the question! Yes that is indeed correct - in RoboAgent we only used joint positions, so did not compute the ee pose but it can be derived from joint positions using forward kinematics. (thanks for flagging the dataset sheet - we will update it to avoid any confusion)

**Comment by hhcaz** [comment]
Got it, thanks for the reply.
