### ISSUE TITLE
Robot ee pose

### ISSUE THREAD

**Issue by Todibo99** [robopen/roboagent#19]
Thanks for sharing such a high quality dataset !!!
Can you opensource the code to derive the ee pose (xyz + quat)? Because I guess we need some robot parameters to do that, e.g. link length.

**Comment by Jdvakil** [comment]
Hi @Todibo99, the code to derive ee pose through inverse kinematics has been open sourced through [RoboHive](https://github.com/vikashplus/robohive/blob/6c14798e48b9904dd8c9151837a1d2468b87bcf3/robohive/envs/fm/franka_robotiq_data_v0.py#L97-L98)
Here is an example of forward kinematics used to derive ee pose from joint angles https://github.com/Jdvakil/kinematics/blob/dbc0b5d5e7d709f4c2ca13df62d7d2abfcc6f3d5/kinematics.py#L7
