### ISSUE TITLE
CVAE usgae in the paper Fig. 5

### ISSUE THREAD

**Issue by SiyuanHuang95** [robopen/roboagent#2]
Dear authors,

thanks for your awesome paper and project. I really enjoy it.

I have small misunderstanding on the CVAE usage in your Figure 5:

The CVAE encoder encodes the "history?" actions a_{1:T} to a latent style embedding. And the paper states "the decoder of the CVAE is the Transformer policy", I cannot understand which part is the Transformer policy in the Figure 5. 

Looking forward to your reply.

**Comment by homangab** [comment]
hmm I am not sure if I understand you question correctly - Fig 5 shows the entire policy architecture (z is the encoding from CVAE) and the Transformer (shown as separate encoder+decoder) blocks is the policy. Note that this is similar to the ACT paper https://arxiv.org/abs/2304.13705 (in case it helps in understanding this better).

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your feedback.

My question raises from the lines:

"""
we incorporate a CVAE that encodes action sequences into latent style embeddings z. The decoder of the CVAE is the Transformer policy that conditions on latents z. 
"""

So it seems that the CVAE decoder is the same thing to the Transformer decoder in the Figure?

**Comment by SiyuanHuang95** [comment]
Got it! Thanks for the updates!
