### ISSUE TITLE
About rpFrankaRobotiqDataRP02 

### ISSUE THREAD

**Issue by solisyke** [robopen/roboagent#20]
i have finished my training， and changed the mj_envs to robohive.
when i run 'python evaluate.py -e rpFrankaRobotiqDataRP02-v0 ...'  seems that Environment 'rpFrankaRobotiqDataRP02' doesn't exist. 
i change to 'rpFrankaRobotiqData' Environment, and set is_hardware False. but it still doesn't work.   the env_info['obs_dict'] doesn't have cameras.

can you tell me how to evaluate the model without hardware?
thanks very much

**Comment by Jdvakil** [comment]
Hi @solisyke, `rpFrankaRobotiqDataRP02-v0` is [`rpFrankaRobotiqData`](https://github.com/vikashplus/robohive/blob/6c14798e48b9904dd8c9151837a1d2468b87bcf3/robohive/envs/fm/__init__.py#L73) but with custom realsense camera ids. 
If you are trying to evaluate the model in sim, you can try commenting out the camera topics in the env

**Comment by YeJX0108** [comment]
> Hi @solisyke, `rpFrankaRobotiqDataRP02-v0` is [`rpFrankaRobotiqData`](https://github.com/vikashplus/robohive/blob/6c14798e48b9904dd8c9151837a1d2468b87bcf3/robohive/envs/fm/__init__.py#L73) but with custom realsense camera ids. If you are trying to evaluate the model in sim, you can try commenting out the camera topics in the env

could you show me how to comment out the camera topics in the env, i donot know how to do. Thanks.
