### ISSUE TITLE
Derivation of pose in Roboset dataset

### ISSUE THREAD

**Issue by lyshuga** [robopen/roboagent#4]
Hi,

Thanks for great paper and dataset. I was wondering regarding the derivation of field "pose" mentioned in dataset description. Unfortunately, it was not available. Is there a script or any other way how you derived Cartesian pos and quat?

**Comment by homangab** [comment]
Thank you for the question! Do you mean robot joint pose? The following keys in the dataset are the respective positions/velocities of the joints at each time-step: 

qp_arm: The joint positions of the arm at the step
qv_arm: The joint velocities of the arm at the step
qp_ee: The positions of the gripper/end effector at the step
qv_ee: The velocities of the gripper/end effector at the step
ctrl_arm: The controls/actions being applied to the arm
ctrl_ee: The controls/actions being applied to the gripper/end effector

Let me know if there is anything else I can clarify regarding your question.
