### ISSUE TITLE
about datesets

### ISSUE THREAD

**Issue by lunalulu** [robopen/roboagent#6]
thanks for your great work！

The paper states that 7,500 trajectories were used from Teleoperation， but upon downloading the dataset, it was discovered that there are actually 9,500 trajectories from Teleoperation. So, should I use these 9,500 data points to train my model?

thanks for your reply~

**Comment by Jdvakil** [comment]
Hey, thank you so much for reaching out. We only used a subset (7,500 trajectories) of the 9,500 because we truncated the data for augmentation timeline. Feel free to use all of the 9,500 data points for your model training.

**Comment by lunalulu** [comment]
THANKS~
@Jdvakil

**Comment by lunalulu** [comment]
@Jdvakil  
Another question, why is the following restriction added to the data, which is equivalent to only 40% of the total data being used for training? thanks for your reply~
`
n = 100        
for i in randfiles:
            l = len(i)
            num = int(n/250 * l)
            for file in range(num):
                files.append(i[file])
`

**Comment by Jdvakil** [comment]
This variable can range up to a maximum of 250 (total trajectories per task). We ran a series of ablation studies aimed at understanding how varying data volumes impact the agent's performance and its ability to generalize.

**Comment by lunalulu** [comment]
@Jdvakil 
thanks, i get it~

**Comment by Jdvakil** [comment]
@lunalulu  btw, we ran the studies for 50, 100, 150, 200, 250 demonstrations

**Comment by lunalulu** [comment]
@Jdvakil  Aren’t the more data the better?

-------------------------------------------------------------------

Another question, I didn’t find the semantic Augmentations part and parameter settings, can you tell me?

Or is there no semantic Augmentations part in the project?

thanks for You~

**Comment by Jdvakil** [comment]
> @Jdvakil Aren’t the more data the better?
We wanted to demonstrate that our agent can perform and generalize over multiple scenes and configurations without depending heavily on a plethora of data.

**Comment by homangab** [comment]
Thanks for the question - the repo currently doesn't have the semantic augmentation scripts. We will be adding them soon (in about 3-4 weeks!)

**Comment by HM102** [comment]
any plans to still add it?

**Comment by leslieburke** [comment]
@homangab any plans to update?

**Comment by homangab** [comment]
Apologies for not posting the update here - we were not able to obtain the required approvals from Meta for releasing the generative model based augmentation code due to some compliance rules. I'll close this issue now, feel free to re-open if there is anything else. Thanks!
