### ISSUE TITLE
about the pretrained weight 

### ISSUE THREAD

**Issue by welen-zhou** [robopen/roboagent#7]
thanks for your great work！ 
and can you share some task's model weight for test !

**Comment by homangab** [comment]
Thanks for the question! We will be updating the repo soon with this (about 3-4 weeks). Note that all our policies are trained on the RoboSet data and for testing, you'll have to deploy on a real Franka Panda arm (we do not have any simulation experiments in this project)

**Comment by homangab** [comment]
Here is the link to policy weights https://huggingface.co/jdvakil/RoboAgent/blob/main/roboagent.ckpt (sorry for the delay in getting back)
