### ISSUE TITLE
about robohive envs?

### ISSUE THREAD

**Issue by lunalulu** [robopen/roboagent#8]
i have finished my training.
when i run 'python evaluate.py -e rpFrankaRobotiqDataRP02-v0'

it throw  a  error:

`File "evaluate.py", line 22, in <module>
    from mj_envs.logger.grouped_datasets import Trace
ModuleNotFoundError: No module named 'mj_envs'`

Because I am a newbie, can you tell me how to create this environment? I have installed robohive~
thanks very much

**Comment by homangab** [comment]
Thanks for the question. This is just a name change issue (the robohive repo was called mj_envs earlier) So just changing robohive -> mj_envs everywhere should work. I can push this update soon as well.
