### ISSUE TITLE
Error when downloading Dataset

### ISSUE THREAD

**Issue by happyflying-web** [robopen/roboagent#9]
When I try to download dataset ,the web shows AccessDenied Error ,which prevents me from downloading dataset. Such as this link https://dl.fbaipublicfiles.com/RoboSet/KinestheticSet/Activities/Pick_banana_place_in_mug.tar.gz

**Comment by happyflying-web** [comment]
Thank you! It is useful to me!

**Comment by happyflying-web** [comment]
Hi~
Maybe because of my network latency, there  still exists some problems of links in this page.  https://robopen.github.io/roboset/kinesthetic.html

**Comment by BrightMoonStar** [comment]
I also encountered the same problem when downloading the **Teleoperation** dataset.
http://dl.fbaipublicfiles.com/RoboSet/TeleoperationSet/Activities/stow_bowl/stow_bowl_place_bowl_scene_3.tar.gz

**Comment by Jdvakil** [comment]
@happyflying-web @BrightMoonStar Sorry for the delay, I pushed some fixes, these problems should be resolved now. I was able to download the dataset from both kinesthetic and teleoperation pages. Please let me know if this persists

**Comment by happyflying-web** [comment]
Thanks, I can download correctly !

**Comment by yihangZhu1729** [comment]
Thank you for your wonderful work! I encounter the same problem of "AccessDenied". Here is a list of files that I failed to download:
(1) [Clean Kitchen] Pick Lid, scene 3
(2) [Clean Kitchen] Cap Lid, scene 3
(3) [Clean Kitchen] Flap-Close Oven, scene 3
(4) [Clean Kitchen] Wipe Counter, scene 3
(5) [Heat Soup] Flap-Open Oven, scene 2
(6) [Heat Soup] Flap-Open Oven, scene 4
(7) [Make Tea] Uncap Lid, scene 2
(8) [Make Toast] Place Toast, scene 1
(9) [Serve Soup] Flap-Open Oven, scene 2
(10) [Serve Soup] Slide-Out Bowl, scene 2
(11) [Serve Soup] Slide-Close Bowl, scene 2

**Comment by Jdvakil** [comment]
Hi @yihangZhu1729, thanks for pointing it out! This is from the teleoperation set right? I will check it out. 
Meanwhile, RoboSet is also hosted on huggingface -- https://huggingface.co/datasets/jdvakil/RoboSet-Teleoperation
This should unblock you for now.
